---
root: true
parser: babel-eslint
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:prettier/recommended
env:
  es6: true
  browser: true
rules:
  semi: off
settings:
  import/resolver:
    babel-plugin-root-import:
      rootPathSuffix: './src'
      rootPathPrefix: '#'
